-- MySQL Script generated by MySQL Workbench
-- Fri Aug 11 07:53:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Lociones_Modelo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Lociones_Modelo` ;

-- -----------------------------------------------------
-- Schema Lociones_Modelo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lociones_Modelo` DEFAULT CHARACTER SET utf8 ;
USE `Lociones_Modelo` ;

-- -----------------------------------------------------
-- Table `Lociones_Modelo`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lociones_Modelo`.`Producto` (
  `idProducto` INT NOT NULL,
  `Nombre Copia` VARCHAR(45) NOT NULL,
  `Nombre Real Marca` VARCHAR(45) NOT NULL,
  `Nombre Real Perfume` VARCHAR(45) NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Precio Producto` FLOAT NOT NULL,
  `Unidades disponibles` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lociones_Modelo`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lociones_Modelo`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Correo electronico` VARCHAR(45) NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  CONSTRAINT `fk_Cliente_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Lociones_Modelo`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cliente_Producto_idx` ON `Lociones_Modelo`.`Cliente` (`Producto_idProducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Lociones_Modelo`.`Proveedor esencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lociones_Modelo`.`Proveedor esencias` (
  `idProveedor` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Precio Producto unitario` FLOAT NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lociones_Modelo`.`Proveedor Frascos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lociones_Modelo`.`Proveedor Frascos` (
  `idProveedor Frascos` INT NOT NULL,
  `Nombre proveedor` VARCHAR(45) NOT NULL,
  `Precio Frasco` VARCHAR(45) NOT NULL,
  `Tamaño frasco` VARCHAR(45) NOT NULL,
  `Color envase` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveedor Frascos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lociones_Modelo`.`Producto_has_Proveedor esencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lociones_Modelo`.`Producto_has_Proveedor esencias` (
  `Producto_idProducto` INT NOT NULL,
  `Proveedor esencias_idProveedor` INT NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `Proveedor esencias_idProveedor`),
  CONSTRAINT `fk_Producto_has_Proveedor esencias_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Lociones_Modelo`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Proveedor esencias_Proveedor esencias1`
    FOREIGN KEY (`Proveedor esencias_idProveedor`)
    REFERENCES `Lociones_Modelo`.`Proveedor esencias` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Producto_has_Proveedor esencias_Proveedor esencias1_idx` ON `Lociones_Modelo`.`Producto_has_Proveedor esencias` (`Proveedor esencias_idProveedor` ASC) VISIBLE;

CREATE INDEX `fk_Producto_has_Proveedor esencias_Producto1_idx` ON `Lociones_Modelo`.`Producto_has_Proveedor esencias` (`Producto_idProducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Lociones_Modelo`.`Producto_has_Proveedor Frascos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lociones_Modelo`.`Producto_has_Proveedor Frascos` (
  `Producto_idProducto` INT NOT NULL,
  `Proveedor Frascos_idProveedor Frascos` INT NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `Proveedor Frascos_idProveedor Frascos`),
  CONSTRAINT `fk_Producto_has_Proveedor Frascos_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Lociones_Modelo`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Proveedor Frascos_Proveedor Frascos1`
    FOREIGN KEY (`Proveedor Frascos_idProveedor Frascos`)
    REFERENCES `Lociones_Modelo`.`Proveedor Frascos` (`idProveedor Frascos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Producto_has_Proveedor Frascos_Proveedor Frascos1_idx` ON `Lociones_Modelo`.`Producto_has_Proveedor Frascos` (`Proveedor Frascos_idProveedor Frascos` ASC) VISIBLE;

CREATE INDEX `fk_Producto_has_Proveedor Frascos_Producto1_idx` ON `Lociones_Modelo`.`Producto_has_Proveedor Frascos` (`Producto_idProducto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
